### ISSUE TITLE
Placeholders for placeholders api not working

### ISSUE THREAD

**Issue by Laikar** [slipcor/PVPStats#15]
I have been trying to use the placeholders in a scoreboard, but i haven't been able to get them even when doing 
/papi parse 
I have tried the ones listed at PlaceholdersAPI's and none seems to resolve
At first i thought it was because i had no stats to display, but even when killing another player and having the data in the database the same still happened

**Comment by slipcor** [comment]
do you use "slipcorpvpstats_kills" and similar? Also, which version are you running?

**Comment by Laikar** [comment]
I was using the ones listed at the [placeholderAPI wiki](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#pvp-stats), but as i see those are outdated, the one you said now just worked.
I suggest adding them to the plugin page and updating them at the PAPI page

**Comment by Laikar** [comment]
I just found a bug related to this, i have 2 kills but the placeholder is only showing one screenshot:
![image](https://user-images.githubusercontent.com/10772237/59792474-91e5f680-92d4-11e9-9e07-5d2a94dcd6d7.png)

**Comment by slipcor** [comment]
ok then back to my question, which plugin version are you using?

**Comment by slipcor** [comment]
I think I have fixed this in a build I am still testing. Testing was not really clear so far, but today I think I got a big step forward. Could you backup your config (!!) and then give this build a try?

http://pa.slipcor.net/pvpstats-1.3.jar 

this revamps the config which was abit fiddly in the last version but there have been several fixes today and last week. Fingers crossed and please report back. I am on my own here and... for me it works :D I tested YML and SQLite, that is all I can do on my own :/

**Comment by Laikar** [comment]
I was using the latest version available on spigot.org, i have tried the new one you provided and the same still happens, i am using MySQL(MariaDB actually, but they are the same). They do update when the server is restarted but not when the plugin is reloaded.

**Comment by slipcor** [comment]
1) So you say is that the stats provided "to" the placeholders do only update when the server restarts?

2) They do not update when you do a kill while the server is running?

3) And the actual command output (/pvpstats top etc) STILL WORKS? (is updated when you kill) - If so then I know where to look. I tried fixing this (that the placeholder API gets updated, there was one place missing a method call)

-----------

If the above is the case then I will have a look, otherwise I have to know what works and what does not work

**Comment by slipcor** [comment]
Wow I really am confused as to how this ever worked --- or IF it ever did. I am pushing a fix to spigot now. 1.3.2 should fix this issue and then we're good to go :)

**Comment by Laikar** [comment]
Yeah, that update fixed everything, thank for your surprisingly quick work
